codecentric/spring-boot-admin

README.md
I think that there is an error on the artifac ID for spring-boot-admin-starter-client
=> Correct ArtifactId for spring-boot-admin-starter-client

spring-boot-admin-docs/src/main/asciidoc/index.adoc, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/config/HipchatNotifierConfiguration.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/notify/HipchatNotifier.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/notify/HipchatNotifierTest.java
I've added notification support for Atlassian HipChat. I'm using this in a live project, so thought I'd share it if you're interested.
=> Added notifier for HipChat

spring-boot-admin-docs/src/main/asciidoc/server-ui-modules.adoc
Should be endpoint and not 'endpint'
=> Typo in Activiti UI Module section

spring-boot-admin-docs/src/main/asciidoc/server.adoc
This PR simply polishes the document.
=> Polish doc

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/ApplicationsController.java
=> Fix applications endpoint hang when there are more then 256 apps

spring-boot-admin-docs/src/main/asciidoc/customizing.adoc, spring-boot-admin-server-ui/src/main/frontend/index.js
fixes #1174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codecentric/spring-boot-admin/1178)
=> #1174 - Custom interceptors for http requests made by the UI

spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/config/InstanceProperties.java, spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/registration/DefaultApplicationFactory.java, spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/registration/ServletApplicationFactory.java, spring-boot-admin-client/src/test/java/de/codecentric/boot/admin/client/registration/DefaultApplicationFactoryTest.java, spring-boot-admin-client/src/test/java/de/codecentric/boot/admin/client/registration/ServletApplicationFactoryTest.java, spring-boot-admin-docs/src/main/asciidoc/client.adoc
With this PR:
- close #804 
- expose a `spring.boot.admin.client.instance.service-path`
=> Add configuration for service-path

spring-boot-admin-client/pom.xml, spring-boot-admin-docs/src/main/asciidoc/client.adoc
=> Remove Jolokia dependnecy

spring-boot-admin-server-ui/src/main/frontend/viewRegistry.js
Seems like there was a missing part in my commit of #1413 
Sorry for the mistake
=> method was not called

spring-boot-admin-docs/src/main/asciidoc/customizing.adoc, spring-boot-admin-server-ui/src/main/frontend/sba-config.js, spring-boot-admin-server-ui/src/main/frontend/shell/navbar.vue, spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/config/AdminServerUiAutoConfiguration.java, spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/config/AdminServerUiProperties.java, spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/web/UiController.java, spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/AbstractAdminUiApplicationTest.java, spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/AdminUiReactiveApplicationTest.java, spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/AdminUiServletApplicationTest.java
=> issue-1417 - filter existing supported languages to a subset of them

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/reactive/InstancesProxyController.java
…ework.http.codec.FormHttpMessageReader#readMono.
=> Improve the caching of request body when running in reactive mode

spring-boot-admin-server-ui/src/main/frontend/i18n/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/login.i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/shell/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/about/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/applications/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/auditevents/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/beans/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/caches/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/configprops/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/env/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/flyway/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/gateway/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/heapdump/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/httptrace/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/jolokia/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/liquibase/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/logfile/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/loggers/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/mappings/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/metrics/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/sessions/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/shell/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/threaddump/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/journal/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/wallboard/i18n.is.json
Glad to contribute Icelandic translation!
=> Add Icelandic translation

spring-boot-admin-server-ui/src/main/frontend/views/instances/logfile/i18n.de.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/logfile/i18n.en.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/logfile/index.vue
Implements the word wrapping in log view as requested in #1481.
=> Implement word wrap in log viewer

spring-boot-admin-docs/src/main/asciidoc/customizing.adoc, spring-boot-admin-samples/spring-boot-admin-sample-servlet/src/main/resources/application.yml, spring-boot-admin-server-ui/src/main/frontend/sba-config.js, spring-boot-admin-server-ui/src/main/frontend/viewRegistry.js, spring-boot-admin-server-ui/src/main/frontend/viewRegistry.spec.js, spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/config/AdminServerUiAutoConfiguration.java, spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/config/AdminServerUiProperties.java, spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/web/UiController.java
the following example will hide `Journal` on navbar.
```
spring:
boot:
admin:
ui:
view-settings:
- name: "journal"
enabled: false
```
=> Allow to hide views via config

spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/registration/RegistrationApplicationListener.java
fixed log info of `scheduled registration task`
=> Fix log info of scheduled registration task

spring-boot-admin-server-ui/src/main/frontend/components/sba-panel.vue
=> #1543: Fix for sticky header not working properly

spring-boot-admin-samples/spring-boot-admin-sample-hazelcast/src/main/java/de/codecentric/boot/admin/SpringBootAdminHazelcastApplication.java
Merge #1552 into a combined branch to get a green build.
=> Merge #1552 into the combined fix branch

spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/AdminUiReactiveApplicationTest.java
=> 1551: Fix failing tests by reusing server instance

.travis.yml, pom.xml
=> Catch flaky tests - rerun failing tests (#1564)

.github/workflows/maven.yml, README.md
Right now, we simply build & test the project. No release stuff included. But GitHub Actions badge is added :D
=> #1573: Adding GitHub actions initial workflow configuration

pom.xml
=> ⬆️ Upgrade to Spring Boot 2.4.2

spring-boot-admin-server-ui/src/main/frontend/views/instances/loggers/service.js
=> Fix ui tests by adding try-catch 

pom.xml
=> Javadoc generation should only log warnings and errors (#1606)

.github/workflows/build-pullrequest.yml
=> Added github action to build pull-requests

.gitignore, pom.xml, spring-boot-admin-samples/spring-boot-admin-sample-custom-ui/pom.xml, spring-boot-admin-server-ui/pom.xml
=> Switch node and npm to frontend-maven-plugin #1553

.github/workflows/build-feature.yml, .github/workflows/build-main.yml, .github/workflows/build-pullrequest.yml, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/eventstore/HazelcastEventStoreWithClientConfigTest.java
=> GitHub actions to build on multiple environments (linux and windows)

spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/web/UiController.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/LegacyEndpointConverters.java
I found some code to simplify when using IDEA to inspect the code, so I submit a PR here.
=> Simplify some code

spring-boot-admin-server-ui/package-lock.json, spring-boot-admin-server-ui/package.json, spring-boot-admin-server-ui/pom.xml
* updated node version to 15.12.0
* updated npm version to 7.6.3
* add logging to npm ci
* updating node-sass to 5.0.0 improved performance
* updated package-lock.json to version 2
=> Improve npm ci build times (see #1688)

spring-boot-admin-docs/src/main/asciidoc/server-notifications.adoc, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/notify/MicrosoftTeamsNotifier.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/notify/MicrosoftTeamsNotifierTest.java
#1718: add customization for messages in Microsoft Teams Notifications via SpEl expressions
=> feat(#1718): add spel parsing to teams notifier

spring-boot-admin-server-ui/src/main/frontend/components/sba-alert.vue, spring-boot-admin-server-ui/src/main/frontend/i18n/index.js, spring-boot-admin-server-ui/src/main/frontend/shell/navbar-item-language-selector.spec.js, spring-boot-admin-server-ui/src/main/frontend/shell/navbar-item-language-selector.vue, spring-boot-admin-server-ui/src/main/frontend/shell/navbar.vue
=> Refactor language switch to own component

spring-boot-admin-docs/src/main/asciidoc/getting-started.adoc
=> Add @EnableScheduling to docs

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerInstanceWebClientConfiguration.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/InstanceExchangeFilterFunctions.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/cookies/CookieStoreCleanupTrigger.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/cookies/JdkPerInstanceCookieStore.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/cookies/PerInstanceCookieStore.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/cookies/package-info.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/config/AdminServerInstanceWebClientConfigurationTest.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/web/client/InstanceExchangeFilterFunctionsTest.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/web/client/cookies/CookieStoreCleanupTriggerTest.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/web/client/cookies/JdkPerInstanceCookieStoreTest.java
=> Cookie handling added to InstanceWebClient (#1768)

spring-boot-admin-server-ui/package-lock.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/metrics/index.vue
=> #1821: fix metrics with missing availableTags-property

spring-boot-admin-server-ui/src/main/frontend/views/instances/loggers/loggers.vue
=> #1805: fix switching scope button for loggers

spring-boot-admin-server-ui/pom.xml, spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/config/AdminServerUiAutoConfiguration.java, spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/web/HomepageForwardingFilterConfig.java, spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/web/reactive/HomepageForwardingFilter.java, spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/config/AdminServerUiAutoConfigurationTest.java
=> 1849: fix forwarding filter for webflux base-paths

pom.xml, spring-boot-admin-server-ui/src/main/frontend/components/font-awesome-icon.js, spring-boot-admin-server-ui/src/main/frontend/components/sba-pagination-nav.vue, spring-boot-admin-server-ui/src/main/frontend/views/journal/i18n.de.json, spring-boot-admin-server-ui/src/main/frontend/views/journal/i18n.en.json, spring-boot-admin-server-ui/src/main/frontend/views/journal/i18n.fr.json, spring-boot-admin-server-ui/src/main/frontend/views/journal/index.vue
closes #1859
https://user-images.githubusercontent.com/1809221/143135425-28f051bb-deba-485e-a88e-a6923630009e.mp4
=> Enhancement as suggested in #1859: Add pagination to journal

spring-boot-admin-server-ui/src/main/frontend/views/instances/auditevents/index.vue
=> #1870: Fix missing audit logs

spring-boot-admin-server-ui/package-lock.json, spring-boot-admin-server-ui/package.json
closes #1829
closes #1830
closes #1831
closes #1832
closes #1833
closes #1834
closes #1835
=> chore(deps): update d3

spring-boot-admin-server-cloud/src/main/java/de/codecentric/boot/admin/server/cloud/discovery/DefaultServiceInstanceConverter.java, spring-boot-admin-server-cloud/src/test/java/de/codecentric/boot/admin/server/cloud/discovery/DefaultServiceInstanceConverterTest.java
=> fix(#1925): fix NPE when metadata value is null

spring-boot-admin-server-ui/src/main/frontend/utils/rxjs.js, spring-boot-admin-server-ui/src/main/frontend/views/applications/index.vue, spring-boot-admin-server-ui/src/main/frontend/views/instances/auditevents/index.spec.js, spring-boot-admin-server-ui/src/main/frontend/views/instances/auditevents/index.vue
=> fix(#1935): auditevents no longer fetched

spring-boot-admin-server-ui/src/main/frontend/components/sba-pagination-nav.spec.js, spring-boot-admin-server-ui/src/main/frontend/components/sba-pagination-nav.stories.js, spring-boot-admin-server-ui/src/main/frontend/components/sba-pagination-nav.vue, spring-boot-admin-server-ui/src/main/frontend/i18n/i18n.de.json, spring-boot-admin-server-ui/src/main/frontend/i18n/i18n.en.json
=> fix(#1964): journal pagination navigation exceeds visible space

.github/workflows/build-feature.yml
windows-2016 will be shut off this year.
=> chore(CI): update to windows-latest

spring-boot-admin-server-ui/src/main/frontend/views/instances/jolokia/m-bean-operation-invocation.vue, spring-boot-admin-server-ui/src/main/frontend/views/instances/jolokia/responseHandler.js, spring-boot-admin-server-ui/src/main/frontend/views/instances/jolokia/responseHandler.spec.js
=> fix(#2024): check jolokia body for error status

spring-boot-admin-docs/src/main/asciidoc/client.adoc
=> chore(#1993): enforce ANSI-colored output

spring-boot-admin-server-ui/src/main/frontend/views/instances/env/refresh.vue
=> fix(#2056): fix application list view

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/domain/values/BuildVersion.java
=> fix(#2058): Optimize the problem of default version number of application list

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/domain/values/StatusInfo.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/domain/values/StatusInfoTest.java
=> fix(#2068): polling health status does not include details

spring-boot-admin-docs/src/main/asciidoc/security.adoc, spring-boot-admin-docs/src/main/asciidoc/server-discovery.adoc, spring-boot-admin-samples/spring-boot-admin-sample-consul/src/main/resources/application.yml, spring-boot-admin-server-cloud/src/main/java/de/codecentric/boot/admin/server/cloud/discovery/DefaultServiceInstanceConverter.java, spring-boot-admin-server-cloud/src/test/java/de/codecentric/boot/admin/server/cloud/discovery/DefaultServiceInstanceConverterTest.java
=> fix: consul handling of metadata

pom.xml
Update to Spring Boot 2.6.11 : https://github.com/spring-projects/spring-boot/releases/tag/v2.6.11
=> chore: update spring boot to latest version

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/IntervalCheck.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/services/IntervalCheckTest.java
Cherry-pick from *master* to *2.6.x*. I didn't test the fix, so be cautious.
(FYI @liran2000 and @SteKoe)
=> fix(#2105): Retry mechanism without delay causing failures

spring-boot-admin-server-ui/src/main/frontend/views/instances/logfile/index.vue
=> feat: download logfile

spring-boot-admin-docs/src/site/asciidoc/server-notifications.adoc, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerNotifierAutoConfiguration.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/notify/RocketChatNotifier.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/config/AdminServerNotifierAutoConfigurationTest.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/notify/RocketChatNotifierTest.java
Adding support for RocketChat notifications
=> Add RocketChat Notifier

spring-boot-admin-server-ui/src/main/frontend/views/external/index.js
=> fix(#2328): Error when rendering external view when 'iframe' property is set to true

spring-boot-admin-server-ui/.jest/jest.setup.js, spring-boot-admin-server-ui/src/main/frontend/plugins/modal/Modal.vue, spring-boot-admin-server-ui/src/main/frontend/plugins/modal/api.js, spring-boot-admin-server-ui/src/main/frontend/plugins/modal/helpers.js, spring-boot-admin-server-ui/src/main/frontend/test-utils.js, spring-boot-admin-server-ui/src/main/frontend/views/applications/applications-list-item.spec.js, spring-boot-admin-server-ui/src/main/frontend/views/applications/applications-list-item.vue, spring-boot-admin-server-ui/src/main/frontend/views/applications/i18n.en.json, spring-boot-admin-server-ui/src/main/frontend/views/applications/instances-list.vue
=> fix(#2324): Shutdown button calls restart endpoint

spring-boot-admin-server-ui/src/main/frontend/views/applications/i18n.de.json, spring-boot-admin-server-ui/src/main/frontend/views/applications/i18n.en.json, spring-boot-admin-server-ui/src/main/frontend/views/applications/index.vue
=> fix(#2338): URI is not updated by search input

spring-boot-admin-docs/src/site/asciidoc/customize_ui.adoc, spring-boot-admin-server-ui/src/main/frontend/components/sba-wave.vue, spring-boot-admin-server-ui/src/main/frontend/sba-config.ts, spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/config/AdminServerUiProperties.java
=> fix(#2428): add missing property for enabling background wave

pom.xml, spring-boot-admin-server-ui/src/main/frontend/views/instances/loggers/loggers.vue
=> #2437: Fixed event handling

spring-boot-admin-server-ui/src/main/frontend/components/sba-checkbox.vue
=> fix(#2626): fix remember-me functionality

spring-boot-admin-server-ui/src/main/frontend/views/instances/details/health-details.vue
=> fix(#2628): add breaking to health details panel

spring-boot-admin-server-ui/src/main/frontend/global.d.ts, spring-boot-admin-server-ui/src/main/frontend/index.html, spring-boot-admin-server-ui/src/main/frontend/index.ts, spring-boot-admin-server-ui/src/main/frontend/sba-settings.js, spring-boot-admin-server-ui/src/main/frontend/views/wallboard/index.vue
=> break word on wallboard

spring-boot-admin-server-cloud/src/test/java/de/codecentric/boot/admin/server/cloud/AdminApplicationDiscoveryTest.java, spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/web/reactive/HomepageForwardingFilter.java, spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/AdminUiReactiveApplicationTest.java, spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/AdminUiServletApplicationTest.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/notify/LetsChatNotifier.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/endpoints/QueryIndexEndpointStrategy.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/InstanceWebProxy.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/AdminApplicationHazelcastTest.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/AdminReactiveApplicationTest.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/AdminServletApplicationTest.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/notify/LetsChatNotifierTest.java
Just some replacements of deprecated elements with pending removal to make logs less verbose.
=> Replaced deprecated elements with pending removal.

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/AbstractEventHandler.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/IntervalCheck.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/StatusUpdateTrigger.java, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/StatusUpdater.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/services/StatusUpdateTriggerTest.java
=> fix: status update trigger (#2719)

spring-boot-admin-docs/src/site/asciidoc/faq.adoc
The feature to refresh properties at runtime is barely documented and google search yielded several similar questions how to enable it in Spring Boot Admin. To finally resolve the confusion, the feature should be documented in the official docs properly.
=> improve docs for env refresh

spring-boot-admin-server-ui/package-lock.json, spring-boot-admin-server-ui/package.json
Hi,
We're facing a issue of security with the version of moment.js.
The vulnerability info: https://security.snyk.io/package/npm/moment
Thanks.
=> Update moment package to version 2.29.4

spring-boot-admin-server-ui/src/main/frontend/components/sba-panel.vue, spring-boot-admin-server-ui/src/main/frontend/views/applications/index.vue
=> #3126: Show version for application group

spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-memory.vue
=> fix(#3243): fix missing config property in details-memory

spring-boot-admin-server-ui/package-lock.json, spring-boot-admin-server-ui/package.json, spring-boot-admin-server-ui/src/main/frontend/mocks/instance/metrics/data.ts, spring-boot-admin-server-ui/src/main/frontend/mocks/instance/metrics/index.ts, spring-boot-admin-server-ui/src/main/frontend/mocks/server.ts, spring-boot-admin-server-ui/src/main/frontend/public/mockServiceWorker.js, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-memory.spec.ts, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-memory.vue
after fixing #3243, this adds test to the component
=> chore(#3243): add tests 

spring-boot-admin-server-ui/package-lock.json, spring-boot-admin-server-ui/package.json
Mitigation of https://github.com/vitejs/vite/issues/19018
=> fix: downgrade esbuild to 0.24.0

spring-boot-admin-server-ui/src/main/frontend/views/instances/mappings/index.spec.ts, spring-boot-admin-server-ui/src/main/frontend/views/instances/mappings/index.vue
=> fix(#4189): add content type validation for mappings component

spring-boot-admin-server-ui/src/main/frontend/views/applications/ApplicationStatusHero.spec.ts, spring-boot-admin-server-ui/src/main/frontend/views/applications/ApplicationStatusHero.vue
=> fix(#4207): update status icons in ApplicationStatusHero component

spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/i18n.en.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/index.vue, spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.spec.ts, spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.vue
=> Fix scheduled tasks view

spring-boot-admin-server-ui/src/main/frontend/views/applications/InstancesList.vue
=> 4254: fix scrollbar in instances list

spring-boot-admin-server-ui/src/main/frontend/global.d.ts, spring-boot-admin-server-ui/src/main/frontend/views/external/index.ts, spring-boot-admin-server-ui/vite.config.mts
=> fix(#4259): iframe in external views do not show up properly

spring-boot-admin-server-ui/src/main/frontend/views/instances/details/health-details.vue
=> add missing class to some health infos

spring-boot-admin-server-ui/src/main/frontend/components/sba-toggle-scope-button.vue, spring-boot-admin-server-ui/src/main/frontend/views/applications/ApplicationStatusHero.vue, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-datasource.vue
=> fix(#4255): convert ApplicationStatusHero to Composition API and improve last update handling

spring-boot-admin-server-ui/src/main/frontend/toast-theme.css
=> fix(#4284): improve scrollbar appearance in toast notifications

spring-boot-admin-server-ui/package-lock.json, spring-boot-admin-server-ui/package.json, spring-boot-admin-server-ui/src/main/frontend/i18n/i18n.de.json, spring-boot-admin-server-ui/src/main/frontend/i18n/i18n.en.json, spring-boot-admin-server-ui/src/main/frontend/i18n/i18n.es.json, spring-boot-admin-server-ui/src/main/frontend/i18n/i18n.fr.json, spring-boot-admin-server-ui/src/main/frontend/i18n/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/i18n/i18n.ko.json, spring-boot-admin-server-ui/src/main/frontend/i18n/i18n.pt-BR.json, spring-boot-admin-server-ui/src/main/frontend/i18n/i18n.ru.json, spring-boot-admin-server-ui/src/main/frontend/i18n/i18n.zh-CN.json, spring-boot-admin-server-ui/src/main/frontend/i18n/i18n.zh-TW.json, spring-boot-admin-server-ui/src/main/frontend/utils/prettyTime.ts, spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/index.vue, spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.spec.ts, spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/scheduled-task-executions.vue
=> feat(#4290): add pretty print for duration in scheduler view

spring-boot-admin-server-ui/package.json, spring-boot-admin-server-ui/src/main/frontend/components/sba-key-value-table.vue, spring-boot-admin-server-ui/src/main/frontend/public/mockServiceWorker.js, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-info.vue, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-process.vue, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/i18n.de.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/i18n.en.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/i18n.es.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/i18n.fr.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/i18n.is.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/i18n.ko.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/i18n.pt-BR.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/i18n.ru.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/i18n.zh-CN.json, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/i18n.zh-TW.json
Also acts as fallback when `/env` is not available as stated in #4242.
closes #4242
=> feat(#4242): use info endpoint to gather additional information for process info

spring-boot-admin-server-ui/src/main/frontend/views/applications/InstancesList.vue
https://github.com/user-attachments/assets/0bc27f32-d2d0-431a-a49e-654ddda8bc18
=> fix: UX in instances list for tags

spring-boot-admin-client/src/test/resources/application.yml, spring-boot-admin-samples/spring-boot-admin-sample-servlet/src/main/resources/application.yml, spring-boot-admin-server-cloud/src/test/resources/application.yml, spring-boot-admin-server-ui/src/main/frontend/components/sba-button.vue, spring-boot-admin-server-ui/src/main/frontend/components/sba-tag.vue, spring-boot-admin-server-ui/src/main/frontend/services/instance.ts, spring-boot-admin-server-ui/src/main/frontend/views/applications/ApplicationListItemAction.vue, spring-boot-admin-server-ui/src/main/frontend/views/applications/InstancesList.vue, spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-nav.vue, spring-boot-admin-server-ui/src/test/resources/application.yml, spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/domain/values/Registration.java, spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/domain/values/RegistrationTest.java, spring-boot-admin-server/src/test/resources/application.yml
closes #4468 
closes #4338 
Documentation of feature follows in another PR.
=> feat: implement ability to override serviceUrl and set hideUrl per instance
