codecentric/spring-boot-admin

spring-boot-admin-server-ui/app/js/service/applicationJmx.js
spring-boot-admin-server-ui/app/js/service/applicationLogging.js

When running the spring-boot-admin-ui behind a proxy server, the jmx view was not working because the urls being used were relative to the root url '/api/application', rather than the application context. This was not the case for other requests, which used api/application' . This change drops the '/' character from the urls so that the javascript calls can be made relative to the application context and thus work behind a http proxy.

Update jolokia javascript urls to support running behind a http proxy

---

spring-boot-admin-server-ui/app/js/controller/overviewCtrl.js
spring-boot-admin-server-ui/app/views/apps.html
spring-boot-admin-server-ui/app/views/apps/details.html
spring-boot-admin-server-ui/app/views/apps/details/classpath.html
spring-boot-admin-server-ui/app/views/apps/details/env.html
spring-boot-admin-server-ui/app/views/apps/details/props.html
spring-boot-admin-server-ui/app/views/overview.html
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/discovery/ApplicationDiscoveryListener.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/registry/ApplicationRegistry.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/registry/HashingApplicationUrlIdGenerator.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/zuul/ApplicationRouteLocator.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/AdminApplicationHazelcastTest.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/AdminApplicationTest.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/controller/RegistryControllerTest.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/discovery/ApplicationDiscoveryListenerTest.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/registry/ApplicationRegistryTest.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/zuul/ApplicationRouteLocatorTest.java
spring-boot-admin-starter-client/src/main/java/de/codecentric/boot/admin/config/AdminClientProperties.java
spring-boot-admin-starter-client/src/main/java/de/codecentric/boot/admin/config/AdminProperties.java
spring-boot-admin-starter-client/src/main/java/de/codecentric/boot/admin/config/SpringBootAdminClientAutoConfiguration.java
spring-boot-admin-starter-client/src/main/java/de/codecentric/boot/admin/model/Application.java
spring-boot-admin-starter-client/src/main/java/de/codecentric/boot/admin/services/ApplicationRegistrator.java
spring-boot-admin-starter-client/src/test/java/de/codecentric/boot/admin/config/AdminClientPropertiesTest.java
spring-boot-admin-starter-client/src/test/java/de/codecentric/boot/admin/model/ApplicationTest.java
spring-boot-admin-starter-client/src/test/java/de/codecentric/boot/admin/services/ApplicationRegistratorTest.java

I've separated the service, management and health URLs, to resolve issues #52 and #56.
The old single-url format is still supported for registration, inferencing the health-url, so you don't have to update all clients.
To register a non-boot app only a healthUrl and a name is required.
Feedback welcome

separate health, management and service url

---

spring-boot-admin-starter-client/src/main/java/de/codecentric/boot/admin/config/SpringBootAdminClientAutoConfiguration.java
spring-boot-admin-starter-client/src/test/java/de/codecentric/boot/admin/config/SpringBootAdminClientAutoConfigurationTest.java

Added inner-class for admin client registration configuration which is conditional on spring.boot.admin.url. Logfile endpoint is now available when just using Spring Cloud Discovery.
Addresses gh-84

Logfile endpoint available when not using spring.boot.admin.url

---

spring-boot-admin-server-ui/app/views/apps/environment.html

added orderBy:’key’ to environment.html to enable alphabetical ordering by key for easier user readability.

order by key for environment key/value pairs

---

spring-boot-admin-starter-client/src/main/java/de/codecentric/boot/admin/config/SpringBootAdminClientAutoConfiguration.java

The RestTamplateBuilder doesn't save the arguments, it returns a new Builder instance, with the saved arguments. So you have to save the builder everytime you call a function on it.

fixed the builder setup, when creating he ApplicationRegistrator.

---

spring-boot-admin-docs/src/main/asciidoc/server-ui-modules.adoc
spring-boot-admin-docs/src/main/asciidoc/server.adoc
spring-boot-admin-samples/spring-boot-admin-sample-eureka/src/main/resources/application.yml
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/config/AdminServerProperties.java

The documentation mentions the endoint "trace" twice in every example. Also, the default configuration in `AdminServerProperties.java` uses the String twice. While this does not cause problems, I think this is a bit irritating. So I suggest removing the second "trace" entry entirely.

removed duplication of endpoint 'trace' in examples and default properties

---

spring-boot-admin-starter-client/src/main/java/de/codecentric/boot/admin/client/config/AdminClientProperties.java

This PR adds a setter so that the documented way of adding credentials for the communication with the clients works.
```
spring:
boot:
admin:
client:
metadata:
user.name: "${security.user.name}"          #These two are needed so that the server
user.password:  "${security.user.password}" #can access the proteceted client endpoints
```

added missing setter for metadata

---

spring-boot-admin-server-ui/modules/applications-details/components/cacheStats.tpl.html

Fixing a display error with cache rowspan when hitRatio is not present

Fix cache stats display when hit/miss ration is missing

---

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/discovery/DefaultServiceInstanceConverter.java

In DefaultServiceInstanceConverter.java, there are two unused imports

Remove unused imports

---

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/registry/ApplicationRegistry.java

This helps to quickly track down configuration problems, especially in systems that generate the config rather than depend on flat files.

Include the invalid URL value in the message

---

README.md

The previous code snippet contained code which would go in the `distributionManagement` section of a POM, meant for where to publish snapshots. It is however intended for users to use in their POMs to access published snapshot versions of the Spring Boot Admin artifacts. This change makes that more clear and gives the correct snippet to copy-and-paste into one's POM.

Fix snapshot build instructions

---

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/notify/MicrosoftTeamsNotifier.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/notify/MicrosoftTeamsNotifierTest.java

The to/from statuses were previously inverted. For example for a status change from OFFLINE to UP the message read:
> \<instance> with id <instance_id> changed status from UP to OFFLINE
this pull request changes this to:
> \<instance> with id <instance_id> changed status from OFFLINE to UP 
Also includes a minor improvement to the registration message:
Before:
> \<instance> with id <instance_id> has registered **from** Spring Boot Admin
After:
> \<instance> with id <instance_id> has registered **with** Spring Boot Admin

[MicrosoftTeamsNotifier] Fix order of to/from statuses in status changed notifications

---

spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/registration/CloudFoundryApplicationFactory.java
spring-boot-admin-client/src/test/java/de/codecentric/boot/admin/client/registration/CloudFoundryApplicationFactoryTest.java

Before this, the route was always lower-cased, but this makes the route registered with Spring Boot Admin not accessible. This changes to use the route as it is, and updates a test to include an uppercase letter in the route.

Fixes Cloud Foundry registration with uppercase letters in route

---

spring-boot-admin-client/pom.xml
spring-boot-admin-server-cloud/pom.xml
spring-boot-admin-server-ui/pom.xml
spring-boot-admin-server/pom.xml

This PR adds `spring-boot-autoconfigure-processor` to improve startup time with auto-configurations.
I confirmed 4 `spring-autoconfigure-metadata.properties` files have been created as follows:
```
$ find . -name spring-autoconfigure-metadata.properties
./spring-boot-admin-client/target/classes/META-INF/spring-autoconfigure-metadata.properties
./spring-boot-admin-server-cloud/target/classes/META-INF/spring-autoconfigure-metadata.properties
./spring-boot-admin-server/target/classes/META-INF/spring-autoconfigure-metadata.properties
./spring-boot-admin-server-ui/target/classes/META-INF/spring-autoconfigure-metadata.properties
$ 
```
Closes gh-815

Add spring-boot-autoconfigure-processor

---

pom.xml
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/InstanceWebClient.java

With Spring Boot 2.1.0.M4 reactor-netty dependency was lifted to 0.8.0.RELEASE.
In this Version reactor.netty.http.client.HttpClient#compress() has a mandatory boolean parameter causing a compilation error in
de.codecentric.boot.admin.server.web.client.InstranceWebClient.
This parameter was set to true.

Updated Spring Boot from 2.1.0.M3 to 2.1.0.M4

---

spring-boot-admin-docs/src/main/asciidoc/index.adoc

_What is Spring Boot Admin?_ still states the UI is written in AngularJS whereas it's Vue.js.

Replace AngularJS with Vue.js

---

spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/web/UiController.java
spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/web/UiControllerTest.java

The scheme of the `spring.boot.admin.ui.public-url` property is ignored.
See https://github.com/codecentric/spring-boot-admin/issues/1007

Preserve scheme from 'spring.boot.admin.ui.public-url' property

---

spring-boot-admin-server-ui/src/main/frontend/components/sba-time-ago.spec.js

Using moment(Number) method creates a moment in the machines local time zone.
This causes the "given a long time passed time" test to fail when running in PST, as it would resolve to Jul 6 and not Jul 7 like the snapshot.

Fix sba-time-ago test

---

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/notify/filter/web/NotificationFilterController.java

The parameters for DELETE /notifications/filters have been renamed while
the error message still used the old parameter names.

Fix message for missing parameters when deleting filters

---

spring-boot-admin-docs/src/main/asciidoc/server-discovery.adoc
spring-boot-admin-server-cloud/src/main/java/de/codecentric/boot/admin/server/cloud/discovery/InstanceDiscoveryListener.java
spring-boot-admin-server-cloud/src/test/java/de/codecentric/boot/admin/server/cloud/discovery/InstanceDiscoveryListenerTest.java

Hi,
I've added filtering of service's instances based on metadata.
There are two new properties:
- `instances-metadata`
- `ignored-instances-metadata`

Add filtering of service's instances based on metadata

---

spring-boot-admin-docs/src/main/asciidoc/changes-2.x.adoc
spring-boot-admin-docs/src/main/asciidoc/client.adoc
spring-boot-admin-docs/src/main/asciidoc/customizing.adoc
spring-boot-admin-docs/src/main/asciidoc/security.adoc
spring-boot-admin-docs/src/main/asciidoc/server-discovery.adoc
spring-boot-admin-docs/src/main/asciidoc/server-notifications.adoc
spring-boot-admin-docs/src/main/asciidoc/server.adoc

I noticed two typos in one of the recent commits and decided to open a pull request to correct it.

Fixed typos in documentation

---

spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/web/UiController.java

This PR changes to use `application/javascript` as [`text/javascript` seems obsolete](https://tools.ietf.org/html/rfc4329#section-7.1).

Use application/javascript

---

spring-boot-admin-server-ui/src/main/frontend/viewRegistry.js

Undefined name prevents creation of nested routed components, because the `router-link` in `sidebar` uses this name as target. Any (custom) instance view that is determined to have any children is therefore unclickable.
In fact I can't see any reason to have undefined name. Maybe there is some, but in such case I would like to know it to be able to design some workaround.

Allow creation of custom nested routed components

---

spring-boot-admin-server-ui/src/main/frontend/views/instances/loggers/i18n.de.json
spring-boot-admin-server-ui/src/main/frontend/views/instances/loggers/i18n.en.json
spring-boot-admin-server-ui/src/main/frontend/views/instances/loggers/loggers-list.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/loggers/loggers.vue

Yes, it's only an issue with Log4j2-Backend.
Logback is creating all loggers along the package-structure. (https://github.com/qos-ch/logback/blob/597b272384cc02f711dbdf6895763e256eddaa76/logback-classic/src/main/java/ch/qos/logback/classic/LoggerContext.java#L141-L142)
Log4j2 only exposes the explicit configured Loggers.
This PR allowes the creation/configuration of loggers (should fix #1256), even if they are not listed by the LoggersEndpoint. In case of Log4J2 you are creating a new logger-configuration. In case of Logback, it might not make any sense to create new loggers, but I see no problem in allowing it.

Allow creation of new Loggers (#1256)

---

spring-boot-admin-server-ui/src/main/frontend/views/instances/env/index.vue

spring-cloud-aws provides instanceData configurations which are missing value properties. This breaks the filtering throwing "TypeError: Cannot read property 'toString' of undefined" of the property.value.toString(). Resolved to check for value property.
Data back from /actuator/env when using spring-cloud-aws:
`{
"name": "InstanceData",
"properties": {
"ami-manifest-path": {
"value": "(unknown)"
},
"public-ipv4": {},
"profile": {
"value": "default-hvm"
},
}`
Notice public-ipv4 is missing value property. 
Wondering if this could be backported to the 2.1.x branch as well?

spring-cloud-aws filterProperty js fix

---

spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/web/servlet/HomepageForwardingFilter.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerWebConfiguration.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/utils/jackson/AdminServerModule.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/utils/jackson/RegistrationDeserializerTest.java

* preparation for #1348
* fix code style issue which exists on master

Create own Jackson module for Spring Boot Admin Server

---

spring-boot-admin-docs/src/main/asciidoc/customizing.adoc
spring-boot-admin-samples/spring-boot-admin-sample-custom-ui/src/index.js
spring-boot-admin-server-ui/babel.config.js
spring-boot-admin-server-ui/package-lock.json
spring-boot-admin-server-ui/package.json
spring-boot-admin-server-ui/src/main/frontend/viewRegistry.js
spring-boot-admin-server-ui/src/main/frontend/viewRegistry.spec.js

Closes #1324
Had to add a babel plugin for the test because of spring-boot-admin-server-ui/src/main/frontend/views/index.js:19 that is executed during the test. (require.context is not a function)
[Didnt find a better way to do it.](https://stackoverflow.com/questions/38332094/how-can-i-mock-webpacks-require-context-in-jest) Another solution would have been to move the GROUP_VIEW constant so the import of it would not trigger the require but it looked in the right place there.
Also, would you be interested to migrate your js code to ts ? I'd like to give a hand if so

Replace custom views instead of appending them

---

spring-boot-admin-docs/src/main/asciidoc/client.adoc
spring-boot-admin-samples/spring-boot-admin-sample-hazelcast/src/main/resources/application.yml

The logfile related property names to activate the logfile actuator endpoints have changed in Spring Boot 2.3.0. This commit updates the documentation to reflect this.

Update logfile property names

---

README.md
spring-boot-admin-docs/src/main/asciidoc/getting-started.adoc
spring-boot-admin-docs/src/main/asciidoc/index.adoc

The Pyctuator project allows integrating Python web applications with
Spring Boot Admin. This commit updates the documentation with a short
example and pointers to further documentation on Pyctuator's main
repository.
Resolves #1460

Update documnetation to include Python support using Pyctuator

---

spring-boot-admin-docs/src/main/asciidoc/server-discovery.adoc
spring-boot-admin-server-cloud/src/main/java/de/codecentric/boot/admin/server/cloud/discovery/DefaultServiceInstanceConverter.java
spring-boot-admin-server-cloud/src/test/java/de/codecentric/boot/admin/server/cloud/discovery/DefaultServiceInstanceConverterTest.java

Currently, the `DefaultServiceInstanceConverter` is accessing the metadata to override the address, port and path for management access. There is not way to override the scheme, this is purely set based on `getServiceUrl`'s scheme.
With this change, the scheme is overridable too. Without setting `management.scheme` to override it, the previous behavior is not breaking.
All parts of the management address are now overridable in a consistent way. The existing test `should_convert_with_metadata` is updated to override all options now. The newly introduced option is referred to in the documentation.

Allowing scheme to be set via metadata

---

spring-boot-admin-server-ui/src/main/frontend/views/instances/jolokia/index.vue

Problem if the MBean Name is very long: 
you do not have a chance to select a domain, because the first column will take the hole screen  (only chance if you zoom out the browser).
So better use "fix" width, 4/5 for the MBeans and 1/5 for the domains.

Problems with Long MBean Names

---

spring-boot-admin-docs/src/main/asciidoc/security.adoc
spring-boot-admin-docs/src/main/asciidoc/server.adoc
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerInstanceWebClientConfiguration.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerProperties.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/BasicAuthHttpHeaderProvider.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/web/client/BasicAuthHttpHeaderProviderTest.java

Use configuration properties as source for instance credentials.  This will allow a more secure way to provide credentials when using spring cloud kubernetes discovery.

Auth with configuration props

---

spring-boot-admin-docs/src/main/asciidoc/security.adoc
spring-boot-admin-docs/src/main/asciidoc/server.adoc

Hi all,
just updated to v2.3.1 and activated instance authentification and found that the default-password property is named default-user-password in the documentation.
see AdminServerProperties
Thanks,
Soeren

misleading documentation for property instance-auth.default-password

---

spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/AdminUiReactiveApplicationTest.java

Merge #1551 into the combined fix branch to get a green build.

Merge the fix for #1551 into the combined fix build

---

spring-boot-admin-samples/spring-boot-admin-sample-hazelcast/src/main/java/de/codecentric/boot/admin/SpringBootAdminHazelcastApplication.java

- upgrading to hazelcast 4.x changed the eviction policy for maps
- the default value ENTRY_COUNT is not valid

Changed the hazelcast eviction max size policy (Fixes #1552)

---

.editorconfig
CONTRIBUTING.md
pom.xml

- updated spring-javaformat-checkstyle plugin and removed duplicate configuration
- added code style settings so IntelliJ formats code to match the checkstyle settings
- added documentation on working with IntelliJ
Closes #1561

Sync code style settings with checkstyle expectations (#1561)

---

spring-boot-admin-samples/spring-boot-admin-sample-servlet/src/main/java/de/codecentric/boot/admin/SpringBootAdminServletApplication.java
spring-boot-admin-server-ui/README.md
spring-boot-admin-server-ui/package-lock.json
spring-boot-admin-server-ui/package.json
spring-boot-admin-server-ui/src/main/frontend/services/instance.js
spring-boot-admin-server-ui/src/main/frontend/services/startup-activator.tree.js
spring-boot-admin-server-ui/src/main/frontend/services/startup-actuator.fixture.spec.json
spring-boot-admin-server-ui/src/main/frontend/services/startup-actuator.js
spring-boot-admin-server-ui/src/main/frontend/services/startup-actuator.spec.js
spring-boot-admin-server-ui/src/main/frontend/utils/iso8601-duration.js
spring-boot-admin-server-ui/src/main/frontend/utils/iso8601-duration.spec.js
spring-boot-admin-server-ui/src/main/frontend/views/instances/startup/i18n.de.json
spring-boot-admin-server-ui/src/main/frontend/views/instances/startup/i18n.en.json
spring-boot-admin-server-ui/src/main/frontend/views/instances/startup/index.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/startup/tree-item.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/startup/tree-table.vue
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerInstanceWebClientConfiguration.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/domain/values/Endpoint.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/LegacyEndpointConverters.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/config/AdminServerInstanceWebClientConfigurationTest.java

closes #1547 
* Navigate through event tree provided by startup actuator endpoint
* Collapse/Expand whole event tree by using the checkbox
* Persists current tree state and restores it on page reload in localStorage (when available)
* Allows navigating to an event by adding `id=<id>` as a query param to the URL

Implement view for actuator endpoint

---

spring-boot-admin-samples/spring-boot-admin-sample-servlet/src/main/java/de/codecentric/boot/admin/SecuritySecureConfig.java

As of now, accessing any of the endpoints served by the spring-boot-actuator (e.g. `/actuator/health`) redirects the user/request to the login page. This prevents (for example) liveness and readiness Kubernetes probes to work.
The current fix sets those endpoints as `permitAll` in the security config.
There were some end of line comments with numbers `// <1>`, I don't know the logic behind them so just left the new entry without it.

Fix allow insecure access to Actuator endpoints

---

src/checkstyle/checkstyle.xml

remove lf property from checkstyle.lf

---

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/BasicAuthHttpHeaderProvider.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/config/AdminServerPropertiesTest.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/web/client/BasicAuthHttpHeaderProviderTest.java
spring-boot-admin-server/src/test/resources/server-config-test.properties

Hi SBA Team,
InstanceCredentials should have a DefaultConstructor, as it is used as Spring ConfigurationProperties.
please see https://github.com/codecentric/spring-boot-admin/issues/1559
thanks,
Soeren

NoArgConstructor for InstanceCredentials, so it can be loaded as ConfigurationProperties

---

pom.xml
spring-boot-admin-server-cloud/pom.xml
spring-boot-admin-server-cloud/src/main/java/de/codecentric/boot/admin/server/cloud/config/AdminServerDiscoveryAutoConfiguration.java
spring-boot-admin-server-cloud/src/test/java/de/codecentric/boot/admin/server/cloud/AdminApplicationDiscoveryTest.java
spring-boot-admin-server-cloud/src/test/java/de/codecentric/boot/admin/server/cloud/config/AdminServerDiscoveryAutoConfigurationTest.java

Use `2020.0.1` (last) instead of `2020.0.0-M3`.
This also brings kubernetes [fabric8 client](https://github.com/fabric8io/kubernetes-client) handle alongside with [official one](https://github.com/kubernetes-client/java)
Close #1644

Upgrade spring cloud dependencies to 2020.0.1

---

.github/workflows/build-main.yml

Use maven repo cache during publish snapshots

---

spring-boot-admin-client/src/test/java/de/codecentric/boot/admin/client/registration/CloudFoundryApplicationFactoryTest.java

**Problem:**
A test method with many individual assertions stops being executed on the first failed assertion, which prevents the remaining ones' execution.
**Solution:**
Using the soft assertions feature, all assertions are executed, and all failures will be reported together. In this refactoring, no original assertion was changed.
**Result:**
_Before:_
```
assertThat(app.getManagementUrl()).isEqualTo("http://application/Uppercase/actuator");
assertThat(app.getHealthUrl()).isEqualTo("http://application/Uppercase/actuator/health");
assertThat(app.getServiceUrl()).isEqualTo("http://application/Uppercase/");
```
_After:_
```
SoftAssertions softly = new SoftAssertions();
softly.assertThat(app.getManagementUrl()).isEqualTo("http://application/Uppercase/actuator"); …
```

Improved execution of grouped assertions

---

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/InstanceExchangeFilterFunctions.java

After upgrading to Spring Boot 2.4.x `LegacyEndpointConverter` was never called.
Switching to the `ClientResponse` builder method, which transforms the existing body directly, instead of changing the body and setting it in two steps, solves the problem.

Fix for #1638

---

spring-boot-admin-server-ui/src/main/frontend/components/sba-alert.spec.js
spring-boot-admin-server-ui/src/main/frontend/components/sba-alert.vue

Noticed an error in the browser console after upgrading to SBA 2.5.0: `TypeError: Cannot read property 'message' of null`, since we were trying to access a property instead of calling the function.

Fix `sba-alert`'s rendering in absence of an error

---

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/InstanceWebClient.java

The fallback solution for not having an instance is to skip
the filter and invoke the next one.
This fallback is already executed during preparation of the
Optional, so the next filter is getting triggered even if not needed.
Solution is to wrap the invocation of the next filter in a lambda
which is only executed when needed.

do not invoke next filter accidentally by preparing fallback

---

spring-boot-admin-server-ui/src/main/frontend/views/instances/details/mem-chart.vue

After the upgrade to SBA 2.5.0, I noticed an error started to appear in the console when accessing the details page of an instance (notice the `NaN`), although rendering seems fine:
```
Error: <path> attribute d: Expected number, "M0,NaNL24.095068694…".
```
I tracked this down to the upgrade of the `d3-scale` library (as part of codecentric/spring-boot-admin@4b72b42), where in https://github.com/d3/d3-scale/pull/241 they started to treat `null` values as `undefined` which get coerced to `NaN`. Just like https://github.com/codecentric/spring-boot-admin/blob/9257bf233144fa342a2b963879a62e2a6bcdf7e6/spring-boot-admin-server-ui/src/main/frontend/views/instances/details/mem-chart.vue#L81, we should also handle `null` values explicitly here. This also resolves the errors in my local setup.

Handle `null` metaspace values explicitly when rendering memory charts

---

spring-boot-admin-server-ui/src/main/frontend/views/instances/caches/caches-list.vue

The Spring Boot Actuator endpoint for clearing caches needs uniquely identifiable caches to clear them. If there are two caches with the same name but in different cache managers SBA fails to reset those, because it's not setting the cache manager parameter.
With this change the cache manager parameter, which is already implemented in instance.js, is set. To not showing the status of this action to every cache with the same name, I changed the status array key from cache name to cache key, which includes the cache manager.

fix: clearing caches with cache manager and cache name

---

pom.xml

* Update spring boot to `2.5.6`
* Update spring cloud to `2020.0.4`
According to [documentation](https://spring.io/blog/2021/09/23/spring-cloud-2020-0-4-has-been-released), spring cloud `2020.0.4` is *compatible with spring boot 2.5.X*

Update spring boot to 2.5.6 and spring cloud to 2020.0.4

---

spring-boot-admin-server-cloud/src/main/java/de/codecentric/boot/admin/server/cloud/discovery/DefaultServiceInstanceConverter.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/domain/values/Tags.java

I'm trying to use spring boot admin inside a k8s cluster.
Due to some weird setup out of my control  (k8s, spring-cloud-kubernetes, ...) when boot-admin retrieve instances, some of them contains a metadata map with empty key.
It's a pb because: 
* When building tags it generates exception that stop continuing to add instances.
* When serializing Registration, we'll get a Jackson error (cannot serialize null key)

fix: Add defensive code to prevent metadata containing null key.

---

spring-boot-admin-server-ui/src/main/frontend/utils/logtail.js
spring-boot-admin-server-ui/src/main/frontend/utils/rxjs.js

fix(#1632): do not stop polling log file when rolled over

---

spring-boot-admin-server-ui/src/main/frontend/views/instances/loggers/loggers.vue

Hi,
when SbaToggleScopeButton is clicked on Logger.vue its own data its changing, but not logger/index.vue (its parent). This is preventing logger/index.vue to change the service from InstanceLoggers to ApplicationLoggers and vice versa. I've added one event $emit to communicate the parent this change.

Emit event when scopes changes

---

spring-boot-admin-server-ui/src/main/frontend/components/sba-action-button-scoped.vue

Hi,
it seems there is an error in component SbaActionButtonScoped. It's binding the currentScope only one way (@event) but it's not passing its current value to the child. I've change it to use v-model as it's used in view logger.vue

Fix sba-toggle-scope-button binding in sba-action-button-scoped

---

spring-boot-admin-server-ui/src/main/frontend/views/applications/applications-list-item.vue
spring-boot-admin-server-ui/src/main/frontend/views/applications/instances-list.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/logfile/index.vue

Hi,
this fixes deprecation warnings for using math calculations without wrapping them in calc.
Kind regards
Thomas

fix(style): Wrap division in calc

---

spring-boot-admin-server-ui/src/main/frontend/views/instances/jolokia/index.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/jolokia/m-bean-operation-invocation.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/jolokia/m-bean-operation.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/jolokia/utils.js
spring-boot-admin-server-ui/src/main/frontend/views/instances/jolokia/utils.spec.js

fix(#1986): improve UX for JMX view

---

spring-boot-admin-server-cloud/src/main/java/de/codecentric/boot/admin/server/cloud/discovery/DefaultServiceInstanceConverter.java

Fixes #1576 . When no port is explicitly set in the configuration, the **ServiceInstance** object received by spring cloud discovery in **InstanceDiscoveryListener** does not return a valid **URI** objet:
```
URI uri = serviceInstance.getURI();
uri.getPort() -> -1
uri.getHost() -> null
```
This URI is used within **DefaultServiceInstanceConverter** and ends failing.
With the commit when port is -1 the URI is built from the ServiceInstance, using default ports, instead of relying in serviceInstance.getURI()

fix(#1576): support http/https default ports in service discovery

---

pom.xml
spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration.java
spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/config/SpringBootAdminClientCloudFoundryAutoConfiguration.java
spring-boot-admin-client/src/main/resources/META-INF/spring.factories
spring-boot-admin-client/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
spring-boot-admin-server-cloud/src/main/java/de/codecentric/boot/admin/server/cloud/config/AdminServerDiscoveryAutoConfiguration.java
spring-boot-admin-server-cloud/src/main/resources/META-INF/spring.factories
spring-boot-admin-server-cloud/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/config/AdminServerUiAutoConfiguration.java
spring-boot-admin-server-ui/src/main/resources/META-INF/spring.factories
spring-boot-admin-server-ui/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerAutoConfiguration.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerCloudFoundryAutoConfiguration.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerHazelcastAutoConfiguration.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerNotifierAutoConfiguration.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/ApiMediaTypeHandler.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/InfoUpdater.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/StatusUpdater.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/endpoints/QueryIndexEndpointStrategy.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/InstanceExchangeFilterFunctions.java
spring-boot-admin-server/src/main/resources/META-INF/spring.factories
spring-boot-admin-server/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/domain/values/InfoTest.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/services/InfoUpdaterTest.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/services/StatusUpdaterTest.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/services/endpoints/QueryIndexEndpointStrategyTest.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/web/AbstractInstancesProxyControllerIntegrationTest.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/web/client/InstanceExchangeFilterFunctionsTest.java

See spring boot 2.7 [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes) and spring cloud 2021.0.3 [release note](https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2021.0-Release-Notes)
The main points of contributions are the following
* adding `AutoConfiguration` annotation on auto configuration classes. Inner classes keeps their `Configuration`classes as specified in the [documlentation](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#new-autoconfiguration-annotation)
* Removing references to deprecated actuator classe and migrate to `ApiVersion` as specified in former [classe](https://github.com/spring-projects/spring-boot/blob/2.6.x/spring-boot-project/spring-boot-actuator/src/main/jav …

Upgrade to spring boot 2.7.0 and spring cloud 2021.0.3

---

spring-boot-admin-server-ui/src/main/frontend/utils/axios.js

fix(#2045): send credential cookies (i.e. session cookies) on ajax requests

---

spring-boot-admin-samples/spring-boot-admin-sample-reactive/src/main/java/de/codecentric/boot/admin/SpringBootAdminReactiveApplication.java

This makes reactive security example somewhat on-par with servlet sample.
I spent an hour trying to do this in my app which uses custom spring.boot.admin.context-path, so I think it could be useful for others.
Maybe I'm wrong with this, but the trick is to understand that /actuator path is not affected by spring.boot.admin.context-path property in reactive application (difference from servlet app).

Make /actuator/health endpoint accessible in Reactive security example

---

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/IntervalCheck.java
spring-boot-admin-server/src/test/java/de/codecentric/boot/admin/server/services/IntervalCheckTest.java

Solution:
Retry mechanism with proper delay via backoff strategy.

ISSUE-2105 Retry mechanism without delay causing failures

---

spring-boot-admin-server-ui/package-lock.json
spring-boot-admin-server-ui/package.json
spring-boot-admin-server-ui/public/mockServiceWorker.js

`findIndex` is part of the source code but not supported in IE11. 
Possible low hanging fruit fix for #2138.

fix: change transpilation target to support IE10+

---

spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/config/AdminServerUiAutoConfiguration.java
spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/config/AdminServerUiProperties.java
spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/config/ReactiveAdminServerUiAutoConfigurationAdminContextPathTest.java
spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/config/ReactiveAdminServerUiAutoConfigurationBothPathsTest.java
spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/config/ReactiveAdminServerUiAutoConfigurationTest.java
spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/config/ReactiveAdminServerUiAutoConfigurationWebfluxBasePathTest.java
spring-boot-admin-server-ui/src/test/java/de/codecentric/boot/admin/server/ui/config/ServletAdminServerUiAutoConfigurationTest.java

Add support for additional paths for HomepageForwardingFilterConfig

---

spring-boot-admin-server-ui/src/main/frontend/services/instance.js

**Steps to reproduce:**
1) register metric with comma in tag value
```
registry.gauge(
"metricWithCommaInTag",
Arrays.asList(Tag.of("tagName", "tagValue, ")),
this,
value -> 1.0
);
```
2) try to add it on Admin Server UI
3) check network in browser:
```{"timestamp":"2022-12-10T11:28:03.310+00:00","status":400,"error":"Bad Request","path":"/actuator/metrics/metricWithCommaInTag"}```
**Expected:**
metric is displayed in Spring Boot Admin.
**Why:**
Because SBA concats all tags into single one `?tag=<key:value>,<key:value>` and Spring will split this string by comma (it is incorrect if the comma is inside tag)
**How should be done**
Should use following syntax: `?tag=<key:value>&tag=<key:value>`

support comma-separated tag values

---

spring-boot-admin-server-ui/.gitignore

If I run a `mvn clean install` locally the UI build creates a coverage folder that appears in git as unmerged changes. This PR just ignores this folder to remove the noise on the git merge.

Ignore the ui coverage folder that is generated during the build

---

README.md

The current README points to and older getting started document. This change simply updates the link.

Point to the current getting started guide

---

.github/workflows/release-to-maven-central.yml

Updates the `revision` property to the next SNAPSHOT version based on the given input and commits the changes to the Repository.

feat(ci): set new SNAPSHOT version after release

---

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/notify/MailNotifier.java

```shell
org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "classpath:/META-INF/spring-boot-admin-server/mail/status-changed.html")
at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:235) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parseStandalone(AbstractMarkupTemplateParser.java:100) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:649) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
at …
```

fix: Fix FileNotFoundException in the mail path

---

spring-boot-admin-docs/src/site/asciidoc/server.adoc

closes #2677 
New changes in Spring Boot 3 now mask all actuator values by default. Additional instructions and a link to Spring Boot's documentation added to server.adoc to inform users how to configure these settings if they want to unsanitize values.

Update server.adoc with Spring Boot 3 changes

---

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/endpoints/ProbeEndpointsStrategy.java

Seeing this error with Spring 6.1.
```     
java.lang.NoSuchMethodError: 'int org.springframework.web.reactive.function.client.ClientResponse.rawStatusCode()'
at de.codecentric.boot.admin.server.services.endpoints.ProbeEndpointsStrategy.lambda$convert$2(ProbeEndpointsStrategy.java:100) ~[spring-boot-admin-server-3.1.7.jar!/:3.1.7]
at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.lambda$exchangeToMono$3(DefaultWebClient.java:410) ~[spring-webflux-6.1.0-M5.jar!/:6.1.0-M5]
```

change deprecated rawStatusCode() method, already removed from spring

---

spring-boot-admin-server-ui/src/main/frontend/views/external/index.spec.ts
spring-boot-admin-server-ui/src/main/frontend/views/external/index.ts
spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/web/UiController.java

fix(#2849): drop replacement of characters in router name for external views

---

spring-boot-admin-server-ui/.storybook/preview.js
spring-boot-admin-server-ui/src/main/frontend/components/sba-input.vue
spring-boot-admin-server-ui/src/main/frontend/components/sba-panel.vue
spring-boot-admin-server-ui/src/main/frontend/composables/useApplicationStore.ts
spring-boot-admin-server-ui/src/main/frontend/notificationcenter.d.ts
spring-boot-admin-server-ui/src/main/frontend/services/instance.ts
spring-boot-admin-server-ui/src/main/frontend/test-utils.ts
spring-boot-admin-server-ui/src/main/frontend/utils/useRouterState.spec.ts
spring-boot-admin-server-ui/src/main/frontend/utils/useRouterState.ts
spring-boot-admin-server-ui/src/main/frontend/utils/useSubscription.ts
spring-boot-admin-server-ui/src/main/frontend/views/applications/applications.spec.ts
spring-boot-admin-server-ui/src/main/frontend/views/applications/index.vue
spring-boot-admin-server-ui/src/main/frontend/views/wallboard/index.vue
spring-boot-admin-server-ui/src/main/frontend/views/wallboard/wallboard.spec.ts
spring-boot-admin-server-ui/src/main/frontend/views/wallboard/wallboard.stories.ts

Well, there is a lot going on in this PR. Main goal was to "just" simplify the common behavior of Wallboard and Applications view where both are using the URL as state management: Whenever a search term is typed into the search box, the URL query params update accordingly in order to have shareable URLs like `/applications?q=spring-boot`. As both views implemented this behavior but differently, I decided to extract this and write tests.
Since Vue 3 common behavior can be extracted using "[composables](https://vuejs.org/guide/reusability/composables.html)". For our case there is a new (and now tested!) composable (i.e. behavior) called `useRouterState` that takes care of syncing an internal state with the state of the URL.
Implementing this for the Wallboard was pretty easy, but …

refactoring: useRouterState

---

spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/config/ClientRuntimeHints.java
spring-boot-admin-samples/spring-boot-admin-sample-servlet-graalvm/src/main/resources/application.yml

I worked on support of native image compilation for my applications and found this error:
```
2023-11-16T11:23:42.765+01:00 ERROR 99225 --- [gistrationTask1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
java.lang.IllegalStateException: couldn't determine local port. Please set spring.boot.admin.client.instance.service-base-url.
at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getLocalServerPort(DefaultApplicationFactory.java:205)
at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getServiceBaseUrl(DefaultApplicationFactory.java:109)
at de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getServiceUrl(ServletApplicationFactory.java:62)
at …
```

Add runtime hints for @EventListener methods

---

spring-boot-admin-server-cloud/src/main/java/de/codecentric/boot/admin/server/cloud/discovery/DefaultServiceInstanceConverter.java

Response of discoveryserver looks like this:

add pattern for management port that is used by spring-cloud-kubernetes-discoveryserver

---

spring-boot-admin-server-ui/src/main/frontend/views/applications/InstancesList.vue

fix(#3059): scrollbar for tags in InstanceList is shown, even when there are none

---

.github/workflows/build-feature.yml
.github/workflows/build-main.yml
.github/workflows/build-pullrequest.yml
.github/workflows/release-to-maven-central.yml

replace 'adopt' with 'temurin'
Note: AdoptOpenJdk is obsolete

chore: use Temurin jdk

---

spring-boot-admin-docs/src/site/asciidoc/customize_ui.adoc
spring-boot-admin-server-ui/src/main/frontend/global.d.ts
spring-boot-admin-server-ui/src/main/frontend/sba-config.ts
spring-boot-admin-server-ui/src/main/frontend/services/instance.spec.ts
spring-boot-admin-server-ui/src/main/frontend/services/instance.ts
spring-boot-admin-server-ui/src/main/frontend/shell/navbar.spec.ts
spring-boot-admin-server-ui/src/main/frontend/tests/setup.ts
spring-boot-admin-server-ui/src/main/frontend/views/applications/InstancesList.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-nav.vue
spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/config/AdminServerUiAutoConfiguration.java
spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/config/AdminServerUiProperties.java
spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/web/UiController.java

closes #2538
Allows to hide service urls globally by setting the property `spring.boot.admin.ui.show-instance-url` to `false` on SBA server side or per instance by passing `hide-url=true` as metadata during instance registration.

feat(#2538): implement configs to hide URLs in UI

---

spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/BasicAuthHttpHeaderProvider.java

SpringBoot 3.4 will remove Base64Utils

refactor: use Base64 instead of Base64Utils

---

spring-boot-admin-server-cloud/src/main/java/de/codecentric/boot/admin/server/cloud/discovery/InstanceDiscoveryListener.java
spring-boot-admin-server-ui/src/main/frontend/views/applications/i18n.de.json
spring-boot-admin-server-ui/src/main/frontend/views/applications/i18n.en.json
spring-boot-admin-server-ui/src/main/frontend/views/applications/index.vue
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerWebConfiguration.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/ApplicationsController.java
spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/RefreshInstancesEvent.java

Implements an POST endpoint `/applications` that triggers refreshing instances from discovery client. A UI button calls the new endpoint using a "confirm button".

feat(#1939): implement UI button to retrigger service detection

---

spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration.java
spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/registration/DefaultApplicationRegistrator.java
spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/registration/RestClientRegistrationClient.java
spring-boot-admin-client/src/test/java/de/codecentric/boot/admin/client/config/ClientPropertiesTest.java
spring-boot-admin-client/src/test/java/de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfigurationTest.java
spring-boot-admin-client/src/test/java/de/codecentric/boot/admin/client/registration/RestClientRegistrationClientTest.java

Adds support for using `RestClient` to register an app, so far only `RestTemplate` or `WebClient` were supported.
I was trying to follow how the other two are implemented, configured and tested. My app using locally build snapshot version can register itself while having only `RestClient` configured.
As a bonus I fixed one typo. Also I've added logging exceptions when registration fails, it was difficult for me to figure out _why_ registration was failing, when Spring Boot Admin was swallowing exceptions. But feel free to reject that part if you feel like it's too much.
Closes #3906.

`RestClient` support

---

spring-boot-admin-server-ui/src/main/frontend/components/sba-status-badge.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/details/health-details.spec.ts
spring-boot-admin-server-ui/src/main/frontend/views/instances/details/health-details.vue

closes #4030 
This PR fixes an issue, when health information are not shown entirely in UI because caused as side effect of fix for bug #3999.

fix(#4030): health information show up properly, when actuator header is v3

---

spring-boot-admin-server-ui/src/main/frontend/views/instances/threaddump/threads-list.vue

Set a maximum width for thread names. Show The full name on hover. Fixes #4154.

Wrap long thread names

---

spring-boot-admin-server-ui/src/main/frontend/composables/useClassnameShortener.spec.ts
spring-boot-admin-server-ui/src/main/frontend/composables/useClassnameShortener.ts
spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/index.vue

fix: prevent overflow of long class names in scheduled tasks page

---

spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-gc.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-health.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-info.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-memory.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-metadata.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-process.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-threads.vue
spring-boot-admin-server-ui/src/main/frontend/views/instances/details/index.vue

fix: update panel state management in details components

---

spring-boot-admin-server-ui/src/main/frontend/index.ts
spring-boot-admin-server-ui/src/main/frontend/views/applications/InstancesList.vue
spring-boot-admin-server-ui/src/main/frontend/views/applications/listItem/ItemInformation.vue
spring-boot-admin-server-ui/src/main/frontend/views/applications/listItem/ItemTags.vue

fix(#4468): update URL display to prevent overflow and improve readability

---

spring-boot-admin-server-ui/src/main/frontend/views/instances/details/health-details.spec.ts
spring-boot-admin-server-ui/src/main/frontend/views/instances/details/health-details.vue

Contents of type "object" are now formatted in a nicer way than just having a JSON one-liner.
closes #4689

feat(#4689): format object details in health component for better readability
